[workspace]

members = [
    "firefly-balius",
    "firefly-cardanoconnect",
    "firefly-cardanosigner",
    "firefly-server",
    "scripts/demo",
    "scripts/deploy",
    "scripts/deploy-contract",
]

exclude = ["wasm"]

resolver = "2"
