[formatter.rustfmt]
command = "rustfmt"
excludes = []
includes = ["*.rs"]
options = ["--edition", "2024", "--config", "skip_children=true"]

[global]
excludes = ["*.lock", "*.patch", ".gitignore", ".gitmodules"]
