services:
  firefly-core:
    image: ghcr.io/gytis-ivaskevicius/firefly-core:latest
    volumes:
      - ./firefly-core.yaml:/etc/firefly/firefly.core.yml:ro
    ports:
      - 5000:5000
      - 5101:5101
    depends_on:
      firefly-cardanoconnect:
          condition: service_started
      firefly-cardanosigner:
          condition: service_started
      postgres:
          condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - http://localhost:5000/api/v1/status
      interval: 15s
      retries: 30

  postgres:
    image: postgres
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_PASSWORD: f1refly
    volumes:
        - firefly-db:/var/lib/postgresql/data
    ports:
        - 5104:5432
    healthcheck:
        test:
            - CMD-SHELL
            - pg_isready -U postgres
        interval: 5s
        timeout: 3s
        retries: 12

  firefly-cardanosigner:
    image: ghcr.io/hyperledger/firefly-cardanosigner:main
    build:
      context: ..
      target: firefly-cardanosigner
    develop:
      watch:
      - action: rebuild
        path: ../firefly-cardanosigner
    command: ./firefly-cardanosigner --config-file /app/config.yaml
    ports:
      - 8555:8555
    volumes:
      - ./wallet:/wallet
      - ./signer.yaml:/app/config.yaml

volumes:
  firefly-db:
