include:
  - docker-compose.common.yaml
services:
  firefly-cardanoconnect:
    image: ghcr.io/hyperledger/firefly-cardanoconnect:main
    build:
      context: ..
      target: firefly-cardanoconnect
    develop:
      watch:
      - action: rebuild
        path: ../firefly-cardanoconnect
    command: ./firefly-cardanoconnect --config-file ./config.yaml
    environment:
      - FIREFLY_CONNECTOR_BLOCKCHAIN_BLOCKFROST_KEY=${BLOCKFROST_KEY}
    ports:
      - 5018:5018
    volumes:
      - connect-contracts:/contracts
      - connect-db:/db
      - ./connect.yaml:/app/config.yaml

volumes:
  connect-contracts:
  connect-db:
