[package]
name = "firefly-cardano-generate-key"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bech32 = "0.11"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
minicbor = "0.25"
pallas-crypto = "0.32"
pallas-primitives = "0.32"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"