name: DevShell Validation
on:
  push:

jobs:
  validate-devshell:
    name: Validate DevShell - ${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: x86_64-darwin
            runner: macos-latest
          - system: aarch64-darwin
            runner: macos-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4.2.1

      - name: 🧰 Setup Nix
        uses: nixbuild/nix-quick-install-action@v29

      - name: 🚀 Eval DevShell for ${{ matrix.system }}
        run: nix eval .#devShells.${{ matrix.system }}.default --apply toString
